version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./logs:/text_emotions/logs/info.log
      - ./db.sqlite3:/text_emotions/db.sqlite3
    ports:
      - "8080:8080"
